//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn
    {
        public int ProduktID { get; set; }
        public string Spakowano { get; set; }
        public string Wyslano { get; set; }
        public string Miejsce { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}
