//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int ProduktID { get; set; }
        public Nullable<int> ZlecenieID { get; set; }
        public string Produkt { get; set; }
        public Nullable<int> IloscZamowiona { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Magazyn Magazyn { get; set; }
        public virtual Zlecenia Zlecenia { get; set; }
        public virtual Spawanie Spawanie { get; set; }
        public virtual Wypalanie Wypalanie { get; set; }
        public virtual Zaginanie Zaginanie { get; set; }
    }
}
